//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 03:45:27 AM EST 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="u_state" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="online"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="u_name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="moto"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="u_mood" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="\u4eca\u5929\u653e\u5047\u4e86"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="u_mobile" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;enumeration value="12345678901"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="u_job" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="IT\u8f6f\u4ef6\u5de5\u7a0b\u5e08"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="u_id" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *             &lt;enumeration value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="u_hometown" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="\u5c71\u897f"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="u_email" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="aaa@XXX.com"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="u_avatar" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="w34353453543r53"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "User")
public class User {

    @XmlAttribute(name = "u_state", required = true)
    protected String uState;
    @XmlAttribute(name = "u_name", required = true)
    protected String uName;
    @XmlAttribute(name = "u_mood", required = true)
    protected String uMood;
    @XmlAttribute(name = "u_mobile", required = true)
    protected long uMobile;
    @XmlAttribute(name = "u_job", required = true)
    protected String uJob;
    @XmlAttribute(name = "u_id", required = true)
    protected byte uId;
    @XmlAttribute(name = "u_hometown", required = true)
    protected String uHometown;
    @XmlAttribute(name = "u_email", required = true)
    protected String uEmail;
    @XmlAttribute(name = "u_avatar", required = true)
    protected String uAvatar;

    /**
     * Gets the value of the uState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUState() {
        return uState;
    }

    /**
     * Sets the value of the uState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUState(String value) {
        this.uState = value;
    }

    /**
     * Gets the value of the uName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUName() {
        return uName;
    }

    /**
     * Sets the value of the uName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUName(String value) {
        this.uName = value;
    }

    /**
     * Gets the value of the uMood property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUMood() {
        return uMood;
    }

    /**
     * Sets the value of the uMood property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUMood(String value) {
        this.uMood = value;
    }

    /**
     * Gets the value of the uMobile property.
     * 
     */
    public long getUMobile() {
        return uMobile;
    }

    /**
     * Sets the value of the uMobile property.
     * 
     */
    public void setUMobile(long value) {
        this.uMobile = value;
    }

    /**
     * Gets the value of the uJob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUJob() {
        return uJob;
    }

    /**
     * Sets the value of the uJob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUJob(String value) {
        this.uJob = value;
    }

    /**
     * Gets the value of the uId property.
     * 
     */
    public byte getUId() {
        return uId;
    }

    /**
     * Sets the value of the uId property.
     * 
     */
    public void setUId(byte value) {
        this.uId = value;
    }

    /**
     * Gets the value of the uHometown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUHometown() {
        return uHometown;
    }

    /**
     * Sets the value of the uHometown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUHometown(String value) {
        this.uHometown = value;
    }

    /**
     * Gets the value of the uEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUEmail() {
        return uEmail;
    }

    /**
     * Sets the value of the uEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUEmail(String value) {
        this.uEmail = value;
    }

    /**
     * Gets the value of the uAvatar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUAvatar() {
        return uAvatar;
    }

    /**
     * Sets the value of the uAvatar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUAvatar(String value) {
        this.uAvatar = value;
    }

}
